apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory   # Let's Encrypt ACME server URL for staging
    email: eashanroy7@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging # secret to store the ACME account private key used by cert-manager to authenticate with Let's Encrypt.
    solvers:
    - http01:
        ingress:
          class: istio